version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./website:/usr/share/nginx/html:ro
    container_name: devops-fase-1-web
    restart: unless-stopped

  dev:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./website:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: devops-fase-1-dev
    profiles:
      - dev
